### ISSUE TITLE
Languages mix

### ISSUE THREAD

**Issue by adamvm** [coders-school/templates#11]
Readme.md is in Polish while rest of content is in English

**Comment by adamvm** [comment]
I can translate Readme file to English. If you accept, please assign me the issue

**Comment by ziobron** [comment]
sure, go with it :)

**Comment by adamvm** [comment]
https://github.com/coders-school/templates/pull/16

**Comment by adamvm** [comment]
Can we merge ?

**Comment by ziobron** [comment]
Merged #16
